@WarehouseWebApi_HostAddress = http://localhost:5055

POST http://localhost:5055/api/warehouses
Content-Type: application/json

{
  "IdProduct": 1,
  "IdWarehouse": 1,
  "Amount": 10,
  "CreatedAt": "2023-01-01T00:00:00Z"
}


###
